/**
 * DO NOT EDIT — GENERATED
 * Generated from schemas/chart.json
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "1.1";
export type BirthDate = string;
export type BirthTime = string;
export type BirthCity = string;
export type Latitude = number;
export type Longitude = number;
export type Timezone = string;
export type Ayanamsa = number;
export type EngineVersion = string;
export type DatetimeLocal = string;
export type DatetimeUtc = string;
export type Timezone1 = string;
export type Lat = number;
export type Lon = number;
export type PlaceLabel = string;
export type ApproximateTime = boolean;
export type JulianDayUt = number;
export type Ayanamsa1 = "KP_NEWCOMB";
export type AyanamsaValueDeg = number;
export type NodeType = "TRUE";
export type HouseSystem = "PLACIDUS";
export type Zodiac = "SIDEREAL";
export type Longitude1 = number;
export type Sign =
  | "Aries"
  | "Taurus"
  | "Gemini"
  | "Cancer"
  | "Leo"
  | "Virgo"
  | "Libra"
  | "Scorpio"
  | "Sagittarius"
  | "Capricorn"
  | "Aquarius"
  | "Pisces";
export type SignDegree = number;
/**
 * @minItems 9
 * @maxItems 9
 */
export type Planets = [
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock,
  PlanetBlock
];
export type Name = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Longitude2 = number;
export type Sign1 =
  | "Aries"
  | "Taurus"
  | "Gemini"
  | "Cancer"
  | "Leo"
  | "Virgo"
  | "Libra"
  | "Scorpio"
  | "Sagittarius"
  | "Capricorn"
  | "Aquarius"
  | "Pisces";
export type SignLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type SignDegree1 = number;
export type HouseOccupied = number | null;
export type Retrograde = boolean;
export type Combust = boolean;
export type SpeedDegPerDay = number;
export type Name1 = string;
export type Index = number;
export type Lord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type DegreeInNakshatra = number;
export type Pada = number;
export type DegreeInPada = number;
export type NavamsaSign =
  | "Aries"
  | "Taurus"
  | "Gemini"
  | "Cancer"
  | "Leo"
  | "Virgo"
  | "Libra"
  | "Scorpio"
  | "Sagittarius"
  | "Capricorn"
  | "Aquarius"
  | "Pisces";
export type StarLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type SubLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type SubSubLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type SignificatorOfHouses = number[];
/**
 * @minItems 12
 * @maxItems 12
 */
export type Houses = [
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock,
  HouseBlock
];
export type House = number;
export type CuspLongitude = number;
export type CuspSign =
  | "Aries"
  | "Taurus"
  | "Gemini"
  | "Cancer"
  | "Leo"
  | "Virgo"
  | "Libra"
  | "Scorpio"
  | "Sagittarius"
  | "Capricorn"
  | "Aquarius"
  | "Pisces";
export type CuspSignLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type CuspNakshatra = string | null;
export type CuspStarLord =
  | ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")
  | null;
export type CuspSubLord =
  | ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")
  | null;
export type CuspSubSubLord =
  | ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")
  | null;
export type Occupants = ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")[];
export type AInStarOfOccupants = (
  | "Sun"
  | "Moon"
  | "Mars"
  | "Mercury"
  | "Jupiter"
  | "Venus"
  | "Saturn"
  | "Rahu"
  | "Ketu"
)[];
export type BOccupants = ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")[];
export type CInStarOfOwner = ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")[];
export type DOwner = ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")[];
export type System = "VIMSHOTTARI";
export type Lord1 = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type YearsRemaining = number;
export type Lord2 = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Start = string;
export type End = string;
/**
 * @maxItems 5
 */
export type UpcomingMdAd =
  | []
  | [MdAdPeriod]
  | [MdAdPeriod, MdAdPeriod]
  | [MdAdPeriod, MdAdPeriod, MdAdPeriod]
  | [MdAdPeriod, MdAdPeriod, MdAdPeriod, MdAdPeriod]
  | [MdAdPeriod, MdAdPeriod, MdAdPeriod, MdAdPeriod, MdAdPeriod];
export type Md = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Ad = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Start1 = string;
export type End1 = string;
export type Md1 = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Ad1 = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Pd = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type Start2 = string;
export type End2 = string;
/**
 * @maxItems 30
 */
export type UpcomingPd = PdPeriod[];
export type Planet = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type V1Score = number;
export type Dignity = number;
export type HousePlacement = number;
export type DigBala = number;
export type Retrograde1 = number;
export type Combustion = number;
export type AspectsNet = number;
export type Base = number;
export type Tier = "STRONG" | "MODERATE" | "WEAK";
export type Notes = string[];
export type Derived = boolean;
export type Strengths = StrengthBlock[];
export type Vargottama = ("Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu")[];
export type DebilitatedInD9 = (
  | "Sun"
  | "Moon"
  | "Mars"
  | "Mercury"
  | "Jupiter"
  | "Venus"
  | "Saturn"
  | "Rahu"
  | "Ketu"
)[];
export type TenthLordWellPlaced = boolean;
export type TenthLordInDusthana = boolean;
export type ComputedAt = string | null;
export type Domain = "career" | "finance" | "relationship";
export type Start3 = string;
export type End3 = string;
/**
 * @minItems 1
 */
export type Triggers = [string, ...string[]];
export type WindowScore = number;
export type Windows = TransitWindow[];
export type Domain1 = "career" | "finance" | "relationship";
export type PrimaryCuspSubLord = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
export type CuspSubLordSignifies = number[];
export type EventPromise = boolean;
export type ActiveDashaLords = (
  | "Sun"
  | "Moon"
  | "Mars"
  | "Mercury"
  | "Jupiter"
  | "Venus"
  | "Saturn"
  | "Rahu"
  | "Ketu"
)[];
export type SupportingSignificators = (
  | "Sun"
  | "Moon"
  | "Mars"
  | "Mercury"
  | "Jupiter"
  | "Venus"
  | "Saturn"
  | "Rahu"
  | "Ketu"
)[];
export type BlockingSignificators = (
  | "Sun"
  | "Moon"
  | "Mars"
  | "Mercury"
  | "Jupiter"
  | "Venus"
  | "Saturn"
  | "Rahu"
  | "Ketu"
)[];
export type BlockingHousesHit = number[];
export type Start4 = string;
export type End4 = string;
/**
 * @minItems 1
 */
export type Triggers1 = [string, ...string[]];
export type WindowScore1 = number;
export type TransitWindows = FeatureTransitWindow[];
export type Status = "aligned" | "partial" | "contradicted" | "no_data";
export type ChunkIds = string[];
export type RawScore = number;
export type ConfidenceTier = "HIGH" | "MEDIUM" | "SPECULATIVE" | "WEAK_SIGNAL";
export type ProbabilityPct = number;

export interface ChartData {
  schema_version: SchemaVersion;
  metadata?: ChartMetadata | null;
  birth: BirthBlock;
  settings: SettingsBlock;
  ascendant: AscendantBlock;
  planets: Planets;
  houses: Houses;
  dashas?: DashaBlock | null;
  strengths?: Strengths;
  divisional?: DivisionalBlock;
  transits?: TransitsBlock;
  prediction_features?: PredictionFeaturesBlock;
}
export interface ChartMetadata {
  birth_date: BirthDate;
  birth_time: BirthTime;
  birth_city: BirthCity;
  latitude: Latitude;
  longitude: Longitude;
  timezone: Timezone;
  ayanamsa: Ayanamsa;
  engine_version: EngineVersion;
}
export interface BirthBlock {
  datetime_local: DatetimeLocal;
  datetime_utc: DatetimeUtc;
  timezone: Timezone1;
  lat: Lat;
  lon: Lon;
  place_label: PlaceLabel;
  approximate_time: ApproximateTime;
  julian_day_ut: JulianDayUt;
}
export interface SettingsBlock {
  ayanamsa: Ayanamsa1;
  ayanamsa_value_deg: AyanamsaValueDeg;
  node_type: NodeType;
  house_system: HouseSystem;
  zodiac: Zodiac;
}
export interface AscendantBlock {
  longitude: Longitude1;
  sign: Sign;
  sign_degree: SignDegree;
}
export interface PlanetBlock {
  name: Name;
  longitude: Longitude2;
  sign: Sign1;
  sign_lord: SignLord;
  sign_degree: SignDegree1;
  house_occupied?: HouseOccupied;
  retrograde: Retrograde;
  combust: Combust;
  speed_deg_per_day: SpeedDegPerDay;
  nakshatra?: NakshatraBlock | null;
  kp?: KpBlock | null;
  significator_of_houses?: SignificatorOfHouses;
  significator_levels?: SignificatorLevels;
}
export interface NakshatraBlock {
  name: Name1;
  index: Index;
  lord: Lord;
  degree_in_nakshatra: DegreeInNakshatra;
  pada: Pada;
  degree_in_pada: DegreeInPada;
  navamsa_sign: NavamsaSign;
}
export interface KpBlock {
  star_lord: StarLord;
  sub_lord: SubLord;
  sub_sub_lord: SubSubLord;
}
export interface SignificatorLevels {
  [k: string]: "A" | "B" | "C" | "D";
}
export interface HouseBlock {
  house: House;
  cusp_longitude: CuspLongitude;
  cusp_sign: CuspSign;
  cusp_sign_lord: CuspSignLord;
  cusp_nakshatra?: CuspNakshatra;
  cusp_star_lord?: CuspStarLord;
  cusp_sub_lord?: CuspSubLord;
  cusp_sub_sub_lord?: CuspSubSubLord;
  occupants?: Occupants;
  significators?: SignificatorLadder | null;
}
export interface SignificatorLadder {
  A_in_star_of_occupants?: AInStarOfOccupants;
  B_occupants?: BOccupants;
  C_in_star_of_owner?: CInStarOfOwner;
  D_owner?: DOwner;
}
export interface DashaBlock {
  system: System;
  birth_balance: BirthBalance;
  current: CurrentDasha;
  upcoming_md_ad?: UpcomingMdAd;
  upcoming_pd?: UpcomingPd;
}
export interface BirthBalance {
  lord: Lord1;
  years_remaining: YearsRemaining;
}
export interface CurrentDasha {
  mahadasha: DashaPeriod;
  antardasha: DashaPeriod;
  pratyantardasha: DashaPeriod;
}
export interface DashaPeriod {
  lord: Lord2;
  start: Start;
  end: End;
}
export interface MdAdPeriod {
  md: Md;
  ad: Ad;
  start: Start1;
  end: End1;
}
export interface PdPeriod {
  md: Md1;
  ad: Ad1;
  pd: Pd;
  start: Start2;
  end: End2;
}
export interface StrengthBlock {
  planet: Planet;
  v1_score: V1Score;
  components: StrengthComponents;
  tier: Tier;
  notes?: Notes;
  derived?: Derived;
}
export interface StrengthComponents {
  dignity: Dignity;
  house_placement: HousePlacement;
  dig_bala: DigBala;
  retrograde: Retrograde1;
  combustion: Combustion;
  aspects_net: AspectsNet;
  base: Base;
}
export interface DivisionalBlock {
  d9?: D9Block | null;
  d10?: D10Block | null;
}
export interface D9Block {
  placements: Placements;
  flags: D9Flags;
}
export interface Placements {
  [k: string]:
    | "Aries"
    | "Taurus"
    | "Gemini"
    | "Cancer"
    | "Leo"
    | "Virgo"
    | "Libra"
    | "Scorpio"
    | "Sagittarius"
    | "Capricorn"
    | "Aquarius"
    | "Pisces";
}
export interface D9Flags {
  vargottama?: Vargottama;
  debilitated_in_d9?: DebilitatedInD9;
}
export interface D10Block {
  placements: Placements1;
  flags: D10Flags;
}
export interface Placements1 {
  [k: string]:
    | "Aries"
    | "Taurus"
    | "Gemini"
    | "Cancer"
    | "Leo"
    | "Virgo"
    | "Libra"
    | "Scorpio"
    | "Sagittarius"
    | "Capricorn"
    | "Aquarius"
    | "Pisces";
}
export interface D10Flags {
  tenth_lord_well_placed: TenthLordWellPlaced;
  tenth_lord_in_dusthana: TenthLordInDusthana;
}
export interface TransitsBlock {
  computed_at?: ComputedAt;
  windows?: Windows;
}
export interface TransitWindow {
  domain: Domain;
  start: Start3;
  end: End3;
  triggers: Triggers;
  window_score: WindowScore;
}
export interface PredictionFeaturesBlock {
  career?: PredictionFeature | null;
  finance?: PredictionFeature | null;
  relationship?: PredictionFeature | null;
}
export interface PredictionFeature {
  domain: Domain1;
  primary_cusp_sub_lord: PrimaryCuspSubLord;
  cusp_sub_lord_signifies?: CuspSubLordSignifies;
  event_promise: EventPromise;
  active_dasha_lords?: ActiveDashaLords;
  dasha_support?: DashaSupport;
  supporting_significators?: SupportingSignificators;
  blocking_significators?: BlockingSignificators;
  blocking_houses_hit?: BlockingHousesHit;
  relevant_strengths?: RelevantStrengths;
  transit_windows?: TransitWindows;
  rag_alignment: RagAlignment;
  raw_score: RawScore;
  confidence_tier: ConfidenceTier;
  probability_pct: ProbabilityPct;
}
export interface DashaSupport {
  [k: string]: number[];
}
export interface RelevantStrengths {
  [k: string]: number;
}
export interface FeatureTransitWindow {
  start: Start4;
  end: End4;
  triggers: Triggers1;
  window_score: WindowScore1;
}
export interface RagAlignment {
  status: Status;
  chunk_ids?: ChunkIds;
}
