"""Internal KP sub-lord lookup engine.

Given a sidereal absolute longitude in decimal degrees, resolve the KP
star lord (nakshatra lord) and sub lord by looking the longitude up in the
committed ``data/kp_249.csv`` table (generated by ``scripts/gen_kp_table.py``).

Conventions (shared with backend/app/engines/nakshatra_engine.py and D020):

* Longitude is normalised into ``[0, 360)`` first.
* All boundary math is done in integer arc-seconds, converted once at entry
  via ``arcsec = round((L % 360) * 3600) % 1_296_000``; floats appear only in
  the output degree fields. This avoids float drift at sub boundaries.
* Each CSV row covers the half-open interval ``[start_arcsec, end_arcsec)``:
  the lower bound is inclusive, the upper bound is exclusive. A longitude that
  lands exactly on a boundary therefore belongs to the row that *starts* at
  that boundary.
* Because the arc-second conversion takes ``% 1_296_000``, the maximum
  reachable value is ``1_295_999`` and ``360`` normalises to ``0``. No
  longitude ever maps to the final row's exclusive ``end_arcsec`` of
  ``1_296_000``, so there is no off-by-one at the table's end.

This module is internal only. It does NOT change the public chart schema and
does NOT add ``planets[].kp`` / ``houses[].kp`` (see D022). The deferred fields
(``sub_index``, ``sub_start_longitude``, ``sub_end_longitude``,
``degree_in_sub``) are returned here for internal/testing use but are not
public schema fields.
"""

from __future__ import annotations

import bisect
import csv
from pathlib import Path

FULL_ZODIAC_ARCSEC = 1_296_000

REPO_ROOT = Path(__file__).resolve().parents[3]
KP_TABLE_PATH = REPO_ROOT / "data" / "kp_249.csv"


def _arcsec(longitude: float) -> int:
    """Normalise a longitude in degrees to an integer arc-second in [0, 1296000).

    Mirrors the nakshatra engine: ``360`` and tiny negatives both wrap to ``0``.
    """
    return round((longitude % 360.0) * 3600.0) % FULL_ZODIAC_ARCSEC


def _load_table() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with KP_TABLE_PATH.open(encoding="utf-8", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            rows.append(
                {
                    "row_index": int(row["row_index"]),
                    "nakshatra_index": int(row["nakshatra_index"]),
                    "nakshatra_name": row["nakshatra_name"],
                    "nakshatra_lord": row["nakshatra_lord"],
                    "sub_index": int(row["sub_index"]),
                    "sub_lord": row["sub_lord"],
                    "start_arcsec": int(row["start_arcsec"]),
                    "end_arcsec": int(row["end_arcsec"]),
                }
            )
    if not rows:
        raise ValueError(f"KP table at {KP_TABLE_PATH} is empty")
    return rows


_TABLE = _load_table()
# Contiguous, sorted lower bounds — enables an O(log n) lookup via bisect.
_STARTS = [row["start_arcsec"] for row in _TABLE]


def get_kp_sub_lord(longitude_deg: float) -> dict[str, object]:
    """Resolve the KP star lord and sub lord for a sidereal longitude.

    Args:
        longitude_deg: Sidereal absolute longitude in decimal degrees. Any
            real value is accepted; it is normalised into ``[0, 360)`` first.

    Returns:
        A dict with at least:
            * ``star_lord`` — nakshatra (star) lord (str)
            * ``sub_lord`` — KP sub lord (str)
            * ``sub_index`` — 1-based sub index within the nakshatra (int)
            * ``sub_start_longitude`` — matched row's start, degrees (float)
            * ``sub_end_longitude`` — matched row's end, degrees (float)
            * ``degree_in_sub`` — degrees from ``sub_start_longitude`` (float)
        Plus internal extras (``nakshatra_index``, ``nakshatra_name``,
        ``row_index``, ``longitude``, ``arcsec``) for testing/diagnostics.
    """
    arcsec = _arcsec(longitude_deg)

    # bisect_right over the sorted start bounds: the matching row is the last
    # one whose start_arcsec <= arcsec. With the half-open [start, end) rule and
    # contiguous rows, this is exactly the row containing the longitude.
    row = _TABLE[bisect.bisect_right(_STARTS, arcsec) - 1]

    start_arcsec = int(row["start_arcsec"])
    end_arcsec = int(row["end_arcsec"])

    return {
        "star_lord": row["nakshatra_lord"],
        "sub_lord": row["sub_lord"],
        "sub_index": row["sub_index"],
        "sub_start_longitude": start_arcsec / 3600.0,
        "sub_end_longitude": end_arcsec / 3600.0,
        "degree_in_sub": (arcsec - start_arcsec) / 3600.0,
        # Internal extras (not part of the public chart schema, per D022).
        "nakshatra_index": row["nakshatra_index"],
        "nakshatra_name": row["nakshatra_name"],
        "row_index": row["row_index"],
        "longitude": arcsec / 3600.0,
        "arcsec": arcsec,
    }
